first_Name = input("What is your first name? ")
last_Name = input("What is your last name? ")
age = int(input("What is your age? "))
weight = input("What is your weight? ")
is_Genius = input("is he genius? ")
print(first_Name+" "+last_Name)
print(first_Name+" is "+str(age)+" years old")
print(weight)
print(is_Genius)
# Type casting
# int()
# float()
# str()
# bool()